name: lint

on:
  push:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Lint
        run: |
          ruff --version
          black --check tools || true
          ruff tools || true
